apiVersion: apps/v1
kind: apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
  labels: 
    apps:home
spec:
  selector :
    matchLabels:
      apps: home
  template:
    metadata:
      name: home
      labels:
        apps: home
      spec:
      containers:
      - name: myhttpd
        image: httpd
        ports:
        - containerPorts: 80
---        

apiVersion: apps/v1
kind: apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
  labels: 
    apps:home
spec:
  selector :
    matchLabels:
      apps: home
  template:
    metadata:
      name: home
      labels:
        apps: home
      spec:
      containers:
      - name: myhttpd
        image: httpd
        ports:
        - containerPorts: 80