apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - host: cloud.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service: 
            name: myappmy-app-home-svc
            port: 
              number: 80
      - pathType: Prefix
        path: /home2
        backend:
          service: 
            name: my-app-home2-svc2
            port: 
              number: 80