apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels: 
    apps: my-app-home-svc
spec:
  selector:
    app: home
  ports:
  - port: 80
    name: httpd
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc-2
  labels: 
    apps: my-app-home2-svc2
spec:
  selector:
    app: home2
  ports:
  - port: 80
    name: nginx
    targetPort: 80