apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels: 
  apps: my-app-home-svc
spec:
  type: NodePort
  selector:
    app: myappmy-app-home-svc
  ports:
  - port: <Port>
    targetPort: <Target Port>
